# Mage Inferno Docker Compose Override Example (https://github.com/mageinferno/magento2-docker-compose)
#
# You can use this file to change any of the defaults supplied in docker-compose.yml
# Copy this file to docker-compose.override.yml. Docker compose will read these changes for you.
#
# Example showing how you can enable composer support in this file:
#
appdata:
  volumes:
    - ./html/bin:/var/www/html/bin
    - ./html/var:/var/www/html/var
    - ./html/vendor:/var/www/html/vendor
#    - ./html/pub:/var/www/html/pub
    - ./html/app/code:/var/www/html/app/code
#    - ./html/app/design:/var/www/html/app/design

#dbdata:
#  volumes:
#    - .docker/db:/var/lib/mysql

#setup:
#  environment:
#    - M2SETUP_USE_ARCHIVE=false
